name: Common Wonder Registry Sync
reader:
  - connector_name: Wonder Registry
    publication_name: common_wonder_registry
    slot_name: anycdc_wonder_registry_1
    tables:
      - businesses
      - country_codes
      - currency_codes

writers:
  - connector_name: Treasury Services
  - connector_name: Payment Gateway

