INSERT INTO "field_types" (
                           field_uuid,
                           field_smallint,
                           field_integer,
                           field_bigint,
                           field_decimal,
                           field_char,
                           field_varchar,
                           field_text,
                           field_date,
                           field_time,
                           field_timestamp,
                           field_timestamp_without_tz,
                           field_boolean,
                           field_json,
                           field_uuidv4

) VALUES
      (
             gen_random_uuid(),
          1,
          1,
          1,
          1.0,
          'char',
          'varchar',
          'text',
          '2025-01-01',
             NULL,
          '2025-01-01 10:00:00',
          '2025-01-01 10:00:00+8:00',
          true,
          '{"key":"value"}',
          gen_random_uuid()
         ),
      (
          gen_random_uuid(),
          1,
          1,
          1,
          1.0,
          'char',
          'varchar',
          'text',
          '2025-01-01',
          NULL,
          '2025-01-01 10:00:00',
          '2025-01-01 10:00:00+8:00',
          true,
          '{"key":"value"}',
          gen_random_uuid()
      ),
      (
          gen_random_uuid(),
          1,
          1,
          1,
          1.0,
          'char',
          'varchar',
          'text',
          '2025-01-01',
          NULL,
          '2025-01-01 10:00:00',
          '2025-01-01 10:00:00+8:00',
          true,
          '{"key":"value"}',
          gen_random_uuid()
      ),
      (
          gen_random_uuid(),
          1,
          100,
          1,
          1.0,
          'char',
          'varchar',
          'text',
          '2025-01-01',
           NULL,
          '2025-01-01 10:00:00',
          '2025-01-01 10:00:00+8:00',
          true,
          '{"key":"value"}',
          gen_random_uuid()
      ),
      (
          gen_random_uuid(),
          1,
          10,
          1,
          1.0,
          'char',
          'varchar',
          'text',
          '2025-01-01',
          null,
          '2025-01-01 10:00:00',
          '2025-01-01 10:00:00+8:00',
          true,
          '{"key":"value"}',
          gen_random_uuid()
      );

UPDATE field_types set field_integer = 2 where 1 = 1;
update field_types set field_integer = 11 where field_integer = 10;
delete from field_types where field_integer = 100;
